name: Pull Request Labeler

on:
  - pull_request_target

jobs:
  triage:
    if: github.repository == 'volantis-x/hexo-theme-volantis'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"