name: npm-publish
on:
  workflow_dispatch:
  # release:
  #   types: [published]

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24 #  npm CLI 的版本需要在 11.5.1 版本或以上才支持 OIDC
        registry-url: https://registry.npmjs.org
    - name: Publish
      run: |
        npm publish
