name: release-please
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 6.x
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    if: github.repository == 'volantis-x/hexo-theme-volantis'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          package-name: hexo-theme-volantis
          include-v-in-tag: false
          target-branch: 6.x

  
