name: Sync Coding

on:
  push:
  release:
    types: [published]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Run Curl
        run: |
            curl -u ${{ secrets.CODING_TOKEN_API }} \
               -v -X POST  'https://volantis-x.coding.net/api/cci/job/387490/trigger' \
               -H 'Content-Type: application/json' \
               -d '
                {
                  "envs": [
                    {
                      "name": "BRANCH",
                      "value": "${{ github.ref_name }}",
                      "sensitive": 0
                    }
                  ]
                }'
